before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: fuL7NaOxhfegGEnPDgvyTwS699TBbisg/yVcBeydQoULrELWAcmzdzR9ZqirybG9xSuQxeQDUbV6aeLYezHU3iN+BnGLzsph0jk3Pv5XbFLc9RBdiAEV3sU0JZVuuzaS2n2p+pJfZY7X9Fa7LgTSv8UAJ4IkLe74YGSgpEx/VTaCLJ6c2OeymdxCCHsDkgCq+ReG53J6cPst4yNYTFzn/WZrL5IjxdqXheEZ4aOmrLRSa1ozgWmHY85NHXK/uMPaeZfcyFs3IAfsBRLmwIaWCCgy59p1Jx8c8BKOuP1Plf87N8PgHn4kDGzZBDDxoaDSKdcXzeLs5KLcneJz3q5OtUEARKr3JzNjsH28PAgtUvM/2OoxMqOOQAHmpkCTzT3vfyqmrRONmrOHxB/E80S6RTQWQoLWh1u7wendyaxtfvzQPAxpKRiUNLYcPYJeZr/2rsL48m5jj1UrU1OSChTFEnvoLyr6yLy9KRYuOjTU2irIRBLlVokPvdwdwBD2Kc0kz6ZuIAuqXp/D5CCbfcGO3+RvKIpduXoMXZtDqRgfUvLzlgZk/mSkQtiYPfa79T7soBgOC+j/PxyjyhgRzpjqHVWtK9y5r9R2Ohwv4KF+SR/jtcGflkoXaZQTdfD5V5UeDeQsLBJJdtsyAEMR0Om+XoF0uL2RUUDI/jr0WM35sok= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
